### PR TITLE
Add asset info extra field for existential_deposit

### PR DESCRIPTION
**Pull request by aliXsed**
First step for #183, before we can trace accounts with dust values.

### CODE REVIEW

**Review by jordy25519 — COMMENTED** [review]
PR looks good to me! I think the existential deposit should never be allowed as `0`, maybe it can be some function of decimal places by default or atleast `1`

**Comment by aliXsed** [comment]
> PR looks good to me! I think the existential deposit should never be allowed as `0`, maybe it can be some function of decimal places by default or atleast `1`

If I force a non-zero setting, I'm afraid it will become very opinionated getting in the way of some possible future use cases of assets for which the creator believes 0 is okay and the accounts should exist all the time. What do you think? @holygits

**Comment by jordy25519** [comment]
I think ED is required as a sensible network policy not a per asset policy. We could make the module configurable as such but probably just over complicates this right now, we should build for the uses cases we have right now not the ones we might have

**Review by jordy25519 — APPROVED** [review]
lgtm!

**Review by KarishmaBothara — APPROVED** [review]

**Pull request merged**
