### PR TITLE
Generic Asset create requires root origin

### PR DESCRIPTION
**Pull request by hoani**
The generic asset create extrinsic can only be called by sudo (root) users.

The sudo account must nominate an account ID as the owner of the generic Asset.

Resolves https://centralitydev.atlassian.net/jira/software/projects/BT/boards/136?selectedIssue=BT-119

### CODE REVIEW

**Comment by mzxyz** [comment]
Nice good, LGTM

**Review by jordy25519 — APPROVED** [review]
💯

**Review by cowboy-bebug — APPROVED** [review]
Nice spotting and re-using `fn create_asset()`!

**Comment by mzxyz** [comment]
> Nice spotting and re-using `fn create_asset()`!

This is really cool finding

**Review by mzxyz — APPROVED** [review]

**Pull request merged**
