### PR TITLE
Chores/merge upstream/zh

### PR DESCRIPTION
**Pull request by mzxyz**
Merge substrate/master from git@github.com:paritytech/substrate.git commit #8d822da

### CODE REVIEW

**Comment by mzxyz** [comment]
list of fixing build/test issues:

1. `bin/node-template/pallets/template/src/mock.rs` 
    Add `Doughnut` and `DelegatedDispatchVerifier ` into `impl system::Trait for Test`

2.  `bin/node/cli/tests/purge_chain_works.rs`
    Replace binary cmd: `substrate` to `plug`

3.  `bin/node/cli/tests/running_the_node_and_interrupt.rs`
    Replace binary cmd: `substrate` to `plug`

**Comment by mzxyz** [comment]
list of files with conflicts:

`Cargo.lock`
`primitives/runtime/src/testing.rs`
`frame/system/src/lib.rs`
`frame/executive/src/lib.rs`
`client/network/src/behaviour.rs`
`bin/node-template/runtime/Cargo.toml`
`bin/node-template/pallets/template/src/lib.rs`

**Comment by mzxyz** [comment]
@holygits @cowboy-bebug  @alexsednz

**Review by cowboy-bebug — APPROVED** [review]
LGTM! there's an error I haven't seen before `does_not_abort` Not sure if we care about this one.

**Review by jordy25519 — APPROVED** [review]
Looks good!

**Pull request merged**
