### PR TITLE
#16 Invalnerables: task 1,2

### PR DESCRIPTION
**Pull request by mzxyz**
#16

### CODE REVIEW

**Review by cowboy-bebug — COMMENTED** [review]
Nice and clean 👍

**Comment by jordy25519** [comment]
This should do the trick 👍 

- Can you write a unit test? for `on_report_peer`
e.g. when the peer id is reserved to verify the behaviour

- Add a comment here about reserved nodes becoming invulnerable to reputation changes
This will print in the help message i.e `plug --help`

https://github.com/plugblockchain/plug-blockchain/blob/3d533cf343484ad56d18135e84338b51942a3646/core/cli/src/params.rs#L108

**Comment by hoani** [comment]
It would be great to add a unit test similar to test_peerset_banned(). In the test we would want show that the node is never banned if it is reserved.
We can ignore the part of test_peerset_banned where we wait for the reputation to recover =)

CI seems to be failing due to a dependency issue - I wrote this guide https://centralitydev.atlassian.net/wiki/spaces/WHO/pages/761102339/Setting+Up+Local+CircleCi+for+Mac which lets us run circle ci on our own PCs without pushing to github (although it will still take ages)

**Comment by cowboy-bebug** [comment]
I think we need to go ~further back~ forward in history. `cennznet/master` requires `srml-consensus` module which was removed in this commit dfe6779dcab59a6b52d61bbe53fdf414f3fc887d

bc276f3c9c36652e738ef1c7f705a5faefd36640 added srml/consensus
86a1dccecf90dd1f7bffb859b629bf295bbfa01b refactored and added some more stuff to srml/consensus <- so maybe use this one?

Edit:
@HaoZhaiX Could u rebase to this commit: ~2b43a43dd0dca9a4bb2e3b3253af0e44f71a56ba~ 86a1dccecf90dd1f7bffb859b629bf295bbfa01b

**Comment by cowboy-bebug** [comment]
Closing as the issue is fixed in the legacy repo.

**Pull request closed without merging**
